@extends('frontend.layouts.master')

@section('content')

    <div class="container-fluid">
        <div class="row">
            <div id="content-wrapper" class="col-12" style="padding:0;">
                <section id="main">
                    <section id="content" class="page-content page-cms page-cms-3">
                        <div class="cms-ajax-content">
                            <div class="container">
                                <h1 class="h3">CONDITIONS GÉNÉRALES DE VENTE ET INFORMATIONS LÉGALES</h1>
                                <p>PDF – Mentions légales et Conditions générales de ventes AyaMarket</p>
                                <ul><li><a href="#identit%C3%A9">ARTICLE 1 - IDENTITÉ DU VENDEUR</a></li>
                                    <li><a href="#conditions">ARTICLE 2 - CHAMP D’APPLICATION ET CONDITIONS</a></li>
                                    <li><a href="#disponibilit%C3%A9">ARTICLE 3 - DISPONIBILITÉ DES PRODUITS</a></li>
                                    <li><a href="#offre">ARTICLE 4 - NOTRE OFFRE ET VOTRE COMMANDE</a></li>
                                    <li><a href="#r%C3%A9tractation">ARTICLE 5 - DROIT DE RÉTRACTATION</a></li>
                                    <li><a href="#prix">ARTICLE 6 - LE PRIX</a></li>
                                    <li><a href="#paiement">ARTICLE 7 - PAIEMENT</a></li>
                                    <li><a href="#garantie">ARTICLE 8 - CONFORMITÉ ET GARANTIE</a></li>
                                    <li><a href="#livraison">ARTICLE 9 - LIVRAISON ET EXÉCUTION</a></li>
                                    <li><a href="#ristournes">ARTICLE 10 - CONDITIONS D’UTILISATION DES BONS DE REDUCTION ET RISTOURNES ACCORDÉS</a></li>
                                    <li><a href="#retours">ARTICLE 11 - POLITIQUE EN MATIÈRE DE RETOURS</a></li>
                                    <li><a href="#r%C3%A9servation">ARTICLE 12 - POLITIQUE EN MATIÈRE DE RÉSERVATION</a></li>
                                    <li><a href="#d%C3%A9fectueux">ARTICLE 13 - PRODUITS DÉFECTUEUX</a></li>
                                    <li><a href="#force">ARTICLE 14 - FORCE MAJEURE</a></li>
                                    <li><a href="#propri%C3%A9t%C3%A9">ARTICLE 15 - PROPRIÉTÉ INTELLECTUELLE</a></li>
                                    <li><a href="#litiges">ARTICLE 16 - TRAITEMENT DES RÉCLAMATIONS ET LITIGES</a></li>
                                </ul><hr><hr><p>&nbsp;</p>
                                <h2 class="h4"><a></a>ARTICLE 1 - IDENTITÉ DU VENDEUR</h2>
                                <p>Nous sommes : AyaMarket Charleroi Adresse e-mail : <a href="mailto:Admin@ayamarket.be">Admin@AyaMarket.be</a> </p>
                                <h2 class="h4"><a name="conditions"></a>ARTICLE 2 - CHAMP D’APPLICATION ET CONDITIONS</h2>
                                <ol><li>Nos conditions générales sont applicables à toutes les offres faites par AyaMarket à vous en qualité de Consommateur (toute personne physique qui acquiert ou utilise des produits ou services exclusivement à des fins non professionnelles).</li>
                                </ol><ol start="2"><li>Nous fournissons uniquement en Belgique. Nous sommes en droit de refuser toute livraison à une adresse de livraison située dans un autre pays.</li>
                                </ol><ol start="3"><li>Pour pouvoir placer une commande, vous devez être âgé d’au moins 18 ans. Si vous n’êtes pas âgé de 18 ans, veuillez faire placer la commande par vos parents ou votre tuteur légal.&nbsp; Nous sommes en droit de refuser toute commande dont nous constatons qu’elle est passée par un mineur.</li>
                                </ol><ol start="4"><li>Si des conditions particulières complémentaires sont applicables en plus des présentes conditions générales, les dispositions précédentes sont également applicables à ces conditions particulières. En cas de contradiction entre nos conditions générales et ces conditions particulières, vous avez le droit, en tant que consommateur, d’invoquer le texte qui vous est le plus favorable.</li>
                                </ol><ol start="5"><li>La réalisation d’une commande sur le site Internet vaut acceptation expresses de nos conditions générales de vente qui sont à tout moment disponibles sur le site AyaMarket.</li>
                                </ol><ol start="6"><li>Une copie téléchargeable et imprimable des présentes conditions générales de vente est disponible avant et pendant votre commande sur le site AyaMarket au format PDF.</li>
                                </ol><h2 class="h4"><a></a>ARTICLE 3 - DISPONIBILITÉ DES PRODUITS</h2>
                                <ol><li>Dans le cas où un ou plusieurs article(s) sont indisponibles au moment de la réalisation de la commande, il nous sera malheureusement impossible d’honorer la commande totalement. Vous serez informé, le cas échéant, au plus tôt par mail et, après contact avec notre service client, aurez la possibilité de modifier ou annuler votre commande.</li>
                                </ol><ol start="2"><li>Dans le cas où un ou plusieurs article(s) sont indisponibles au moment de la réalisation de la réservation d’articles en magasin, il nous sera malheureusement impossible de réserver pour vous tous les articles sélectionnés. Vous serez informé, le cas échéant, au plus tôt par mail.</li>
                                </ol><h2 class="h4"><a name="offre"></a>ARTICLE 4 - NOTRE OFFRE ET VOTRE COMMANDE</h2>
                                <ol><li>Lorsqu’une offre n’est valable que pendant une période limitée ou qu’elle est soumise à certaines conditions, nous l’indiquons expressément dans notre offre.</li>
                                </ol><ol start="2"><li>Nous décrivons toujours aussi complètement et précisément que possible ce que nous vous vendons et comment le processus de commande se déroulera. La description est toujours suffisamment détaillée pour vous permettre de l’évaluer correctement. Si nous avons recours à des illustrations, elles présentent fidèlement les biens et/ou services proposés. L’erreur est toutefois humaine, de sorte que s’il apparaît clairement que nous nous sommes trompés, nous ne sommes pas tenus de vous fournir un bien ou service correspondant à l’illustration.</li>
                                </ol><ol start="3"><li>En cas de paiement de la transaction avec une carte de crédit ou de débit, votre commande n’est complète et le contrat entre nous n’est définitif que lorsque nous obtenons l’accord de l’émetteur de la carte. Nous acceptons Visa, MasterCard et Maestro (Bancontact) de la plupart des grandes banques belges. Nous ne pouvons être tenus responsables des retards dans la livraison et/ou de l’absence de livraison de votre commande qui sont dus au refus de l’émetteur de votre carte d’effectuer votre paiement. Les commandes qui ne sont pas accompagnées d’un paiement valable au nom du titulaire de la carte ne sont pas acceptées ou traitées.</li>
                                </ol><ol start="4"><li>Le processus de&nbsp; commande sur l’eshop AyaMarket se déroule comme suit :</li>
                                </ol><p>Vous sélectionnez les articles que vous souhaitez commander et vous les ajoutez à votre panier. Sur la page panier, vous pourrez ensuite cliquer sur le bouton « Procédez à la commande ». Afin de poursuivre votre commande, vous devez vous identifier ou vous créer un compte sur l’eshop AyaMarket. Certaines coordonnées seront demandées afin de mener à bien le traitement de votre commande. Vous pourrez choisir votre mode de livraison parmi ceux proposés par Bpost en remplissant les informations requises. Vous serez informé, avant la validation définitive de votre commande, de tous les frais de livraison applicables à votre commande, le cas échéant.&nbsp; Votre commande ne sera valide que lorsque vous aurez fourni ces informations, pris connaissance et accepté les conditions générales de vente et procédé avec succès au paiement de votre commande en cliquant sur le bouton de commande accompagné de la mention « Payer », ceci via le système de paiement de notre prestataire INGENICO. La commande peut être à tout moment modifiée avant la validation finale. Une fois le paiement effectué, vous pouvez imprimer les détails de votre commande et suivre son statut sur votre compte personnel. Un accusé de réception vous sera envoyé automatiquement par mail, reprenant les détails de votre commande. L´accusé de réception ne représente pas une acceptation de notre part de votre commande: l´accusé de réception vous confirme uniquement que nous avons reçu votre commande. Un mail de confirmation d’envoi des produits, reprenant le lien de suivi de livraison, vous sera ensuite envoyé. La livraison des produits vaut pour acceptation de notre part de votre commande. La livraison ne sera effectuée qu’après réception du paiement de la commande.</p>
                                <ol start="5"><li>Nous nous réservons le droit de refuser votre commande, dans les circonstances:</li>
                                </ol><p>Où les produits sont indisponibles ou épuisés ; Où les produits font l’objet d’une présentation erronée et non valable dans l’eshop ; Où des doutes sérieux d’abus de droit ou de mauvaise foi de la part du client se présentent ; Où un cas de force majeure se produit. Dans le cas où nous n’exécutons pas la commande, le client en sera informé au plus tôt.</p>
                                <h2 class="h4"><a></a>ARTICLE 5 - DROIT DE RÉTRACTATION</h2>
                                <ol><li>Si vous nous achetez des produits en ligne, vous disposez d’un délai de 14 jours à partir de la livraison pour décider que vous ne voulez pas conserver ces produits. Dans ce cas, vous pouvez renvoyer la commande sans devoir payer une amende ni justifier votre décision (les frais du renvoi sont à votre charge).&nbsp; Si vous renvoyez votre commande ou que vous souhaitez renoncer au contrat dans les 14 jours qui suivent votre commande, nous vous remboursons l’intégralité du prix d’achat par le même mode de paiement que celui que vous avez utilisé.&nbsp;Dans le cas où une commande est payée en partie ou totalement avec un bon à valoir ou un chèque cadeau, le remboursement se fera en partie ou totalement avec un nouveau bon à valoir.</li>
                                </ol><ol start="2"><li>Les frais directs du renvoi des biens sont donc à votre charge. Nous vous informerons du coût du renvoi ou, s’il est raisonnablement impossible de les déterminer préalablement, nous vous en donnerons une estimation. S’il est impossible de renvoyer les biens par la poste, nous vous invitons à retourner votre achat gratuitement dans l’un de nos magasins.</li>
                                </ol><ol start="3"><li>Nous avons le droit d’attendre d’avoir récupéré les biens ou que vous ayez prouvé les avoir renvoyés, selon celui de ces deux événements qui intervient en premier, avant de procéder à leur remboursement.</li>
                                </ol><ol start="4"><li>Pendant les 14 premiers jours qui suivent la livraison, nous attendons de vous que vous traitiez la commande et l’emballage avec soin. Si vous souhaitez pouvoir renvoyer les biens conformément à la procédure décrite ci-dessus, vous ne pouvez les déballer ou les utiliser que dans la mesure nécessaire pour pouvoir évaluer si vous souhaitez conserver le bien. Les biens renvoyés peuvent avoir été essayés, mais pas utilisés. Dans la mesure du possible, les biens renvoyés doivent être placés dans leur emballage original et accompagnés de l’ensemble des accessoires livrés. Ils doivent être dans leur état et leur emballage d'origine, compte tenu des instructions mentionnées ci-dessous.</li>
                                </ol><ol start="5"><li>Vous pouvez renvoyer le colis par Bpost ou le déposer dans l’un de nos magasins. (Voir Article 11 – Politique en matière de retours)</li>
                                </ol><ol start="6"><li>Pour exercer rapidement et correctement votre droit de rétractation, le renvoi des produits doit être accompagné soit d'un bon de retour, disponible dans votre colis, soit d’une déclaration libre mais dénuée d’ambiguïté. Vous pouvez aussi utiliser le modèle de formulaire de rétractation, situé en annexe, à envoyer à Admin@AyaMarket.be mais ce n’est pas obligatoire.</li>
                                </ol><ol start="7"><li>Les produits retournés qui ne répondent pas aux conditions mentionnées aux points 5.1 et 5.4 restent votre propriété. Nous vous renvoyons les produits concernés et vous facturons les frais occasionnés.</li>
                                </ol><h2 class="h4"><a name="prix"></a>ARTICLE 6 - LE PRIX</h2>
                                <ol><li>Sauf en cas de modification des tarifs de la TVA, nos prix ne seront pas modifiés pendant la période mentionnée dans notre offre. Les offres et les prix pratiqués par AyaMarket sont valables tant qu´ils sont affichés et dans la limite des stocks disponibles.</li>
                                </ol><ol start="2"><li>Nos prix s’entendent toutes taxes, TVA et services compris, de sorte que vous n’avez jamais de mauvaise surprise.&nbsp; Nous pouvons par contre décider de facturer les frais d’envoi en plus du prix d’achat, auquel cas nous le mentionnons toujours avant que vous ne passiez définitivement commande.</li>
                                </ol><p style="text-align:right;"><a href="#haut">↑ Haut</a></p>
                                <h2 class="h4"><a name="paiement"></a>ARTICLE 7 - PAIEMENT</h2>
                                <ol><li>Le paiement de produits achetés sur le site www.AyaMarket.be se fait exclusivement d’avance, par carte de crédit ou débit via le service PAYPAL. AyaMarket conserve la pleine propriété des marchandises jusqu’au moment de leur parfait acquittement.</li>
                                </ol><ol start="2"><li>Paypal accepte uniquement les modes de paiement suivants&nbsp;: Visa, MasterCard, Maestro (Bancontact)</li>
                                </ol><ol start="3"><li>Certaines méthodes de paiement présentent des restrictions propre à l'organisme de paiement. <a href="https://www.paypal.fr">FAQ de l'application Paypal</a></li>
                                </ol><ol start="4"><li>Le paiement ne peut se faire sur notre site Internet.</li>
                                </ol><ol start="5"><li>Paypal assure la sécurité des payement.</li>
                                </ol><h2 class="h4"><a name="garantie"></a>ARTICLE 8 - CONFORMITÉ ET GARANTIE</h2>
                                <ol><li>Nous garantissons que nos biens sont conformes à votre commande et qu’ils répondent aux attentes normales que vous pouvez avoir, compte tenu des spécifications du produit. Nous vous garantissons aussi bien entendu que nos biens sont conformes à l’ensemble des lois en vigueur au moment de votre commande.</li>
                                </ol><ol start="2"><li>En ce qui concerne la livraison de biens, nous appliquons également le délai de garantie minimum légal de deux ans si le bien n’est pas conforme à la commande placée. Cette garantie implique que tout bien qui présente des vices ou des défauts sera réparé ou remplacé gratuitement jusqu’à 2 ans après sa livraison.</li>
                                </ol><ol start="3"><li>Pour autant que ce soit possible et raisonnable, vous avez le choix entre réparation ou remplacement. Vous n’avez le droit d’exiger une réduction du prix ou la résolution du contrat de vente que si la réparation ou le remplacement s’avère excessif ou impossible ou encore s’il ne peut intervenir dans un délai raisonnable.</li>
                                </ol><ol start="4"><li>Tout défaut ou vice qui se manifeste dans les 6 mois qui suivent la livraison est réputé avoir existé avant la livraison, à moins que nous ne soyons en mesure de prouver le contraire. Au-delà de 6 mois, c’est à vous qu’il appartiendra de prouver que le vice existait avant la livraison.</li>
                                </ol><h2 class="h4"><a name="livraison"></a>ARTICLE 9 - LIVRAISON ET EXÉCUTION</h2>
                                <ol><li>Tous les biens et services sont livrés à l’adresse que vous indiquez lors de la commande. Dans le cas où l’adresse que vous avez indiquée est incorrecte, il en sera de votre responsabilité et pourra vous entraîner des frais supplémentaires.</li>
                                </ol><ol start="2"><li>3 modes de livraison sont possibles via Bpost en Belgique :</li>
                                </ol><ul><li>à domicile ou au bureau</li>
                                    <li>à un point de retrait Bpost</li>
                                    <li>via Bpack 24/7 dans un distributeur automatique.</li>
                                </ul><p>Selon le montant total de votre commande, des frais d’envoi de 4€50 peuvent être facturés. Ceux-ci sont offerts à partir de 50€ d’achats TVAC. Pour la France et le Luxembourg, des frais d'envoi de 9€50 pour la France et &nbsp;7€50 pour le Luxembourg seront facturés, qu'importe le montant de la commande. Lors de la procédure de commande, vous serez informé des éventuels frais d'envoi. Ceux-ci sont calculés définitivement à la fin du processus de commande, avant l’étape « Procéder au paiement » et avant que le paiement ne soit traité par notre prestataire INGENICO.</p>
                                <ol start="3"><li>Les risques supportés vous seront transférés lors la livraison effective du produit à l’adresse que vous avez indiqué. A partir de ce moment, nous déclinons toute responsabilité en cas de perte ou de destruction du produit.</li>
                                </ol><ol start="4"><li>Les produits sont livrés, dans la mesure du possible, dans un délai de 2 à 8 jours ouvrés après la validation de la commande. Nous vous communiquons le délai de livraison lors du processus de commande, avant l’étape du paiement. Dans le cas où nous serions dans l’impossibilité de livrer endéans ce délai, nous vous en informerons au plus tôt. En aucun cas, un éventuel retard ne donnera lieu à une indemnisation.</li>
                                </ol><ol start="5"><li>Dans le cas exceptionnel où nous sommes dans l’impossibilité de livrer la commande dans les 30 jours à dater de la validation de la commande, vous pourrez résilier le contrat de vente en contactant notre service client. Les produits commandés seront remboursés intégralement (en ce compris les frais d'envoi dans le cas où vous les avez pris en charge) dans un délai de 30 jours.</li>
                                </ol><ol start="6"><li>Vous devez vous assurer vous-même que les produits conviennent à vos besoins et sont conformes à vos attentes. Nous ne garantissons pas que les produits soient conformes à vos exigences individuelles. Les produits sont standards et n’ont pas été conçus sur mesure. Pour toute contestation, vous pouvez contacter notre service client.</li>
                                </ol><ol start="7"><li>Dans le cas où les produits sont endommagés pendant le transport ou que les produits livrés diffèrent des produits commandés, vous êtes tenu de nous le signaler aussi rapidement que possible et dans tous les cas endéans les 3 jours, en contactant notre service client.</li>
                                </ol><ol start="9"><li>Nous déclinons toute responsabilité pour tout dommage indirect provoqué par la livraison tardive ou l’absence de livraison par Bpost. Dans ce cas, notre responsabilité reste limitée à la valeur des articles dont il est prouvé qu’ils n’ont pas été reçus par le client.</li>
                                    <li>Retrait en magasin : Vous pouvez également réserver gratuitement vos produits dans un magasin AyaMarket de votre choix. Ceux-ci seront réservés à votre nom durant 7 jours ouvrés (3 jours en période de promotion) à partir du moment où ils sont mis de côté dans le magasin de votre choix. Le paiement s’effectuera directement en magasin.</li>
                                    <li>Nos envois sont toujours effectués à nos risques. Vous ne devez donc pas vous inquiéter si des biens se perdent pendant leur envoi postal. En revanche, si vous nous renvoyez des biens dans les 14 jours qui suivent l’achat, parce que vous ne souhaitez pas les conserver, c'est vous qui êtes responsable de leur transport.</li>
                                    <li>Lors de la livraison du colis, il est du ressort du client de vérifier l'intégralité de la commande avant d'apposer sa signature sur un document officiel. Si un colis semble être endommagé, abîmé, ouvert, il est de la responsabilité du client d'en décliner la réception en le notifiant au prestataire de livraison. Le colis sera automatiquement retourné à l'expéditeur sans frais.&nbsp;</li>
                                </ol><p>Si les biens livrés par nos soins sont endommagés pendant le transport, qu'ils ne correspondent pas aux articles mentionnés sur le bon de livraison ou ne correspondent pas aux articles que vous avez commandés, vous êtes tenu de le signaler aussi rapidement que possible et dans tous les cas dans les 3 jours, et de nous renvoyer les articles dans les 14 jours calendrier qui suivent leur réception. Pour ce faire, veuillez nous contacter à <a href="mailto:Admin@AyaMarket.be">Admin@AyaMarket.be</a>.</p>
                                <h2 class="h4"><a name="ristournes"></a>ARTICLE 10 - CONDITIONS D’UTILISATION DES BONS DE REDUCTION ET RISTOURNES ACCORDÉS</h2>
                                <h4 class="h5">1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Carte de fidélité informatisée</h4>
                                <ul><li>La carte de fidélité informatisée est proposée uniquement aux personnes physiques majeures. Elle est valable dans tous nos magasins et en ligne sur AyaMarket.be.</li>
                                    <li>Elle vous permet de recevoir des informations concernant nos actions et promotions, de bénéficier de certains avantages en ligne et/ou en magasin ainsi que d’accumuler des points lors de tous vos achats, en magasin ou en ligne (1 euro = 1 point) afin de vous attribuer un statut. Vos données sont encodées dans notre système informatique dès votre premier achat. Vos achats sont ensuite encodés sur votre carte virtuelle.</li>
                                    <li>Lors de votre 11ème achat en ligne, vous bénéficiez d’une ristourne, valable en ligne équivalente à 5% du montant de vos 10 premières commandes en ligne.</li>
                                    <li>Un chèque fidélité valable en ligne vous sera remis une fois par an, fin août, et vous fera bénéficier d’une ristourne équivalente à 5% du montant de vos achats antérieurs en ligne, quel que soit votre nombre d’achats, uniquement dans le cas où vous n’avez pas atteint les 10 commandes.</li>
                                    <li>Les commandes en ligne et les passages caisses en magasin ne peuvent pas être combinés pour la ristourne et le chèque fidélité.</li>
                                    <li>Le règlement et le fonctionnement détaillés du système de fidélité demandez à l’adresse <a href="http://www.AyaMarket.be/contact">Contactez-nous</a></li>
                                </ul><h4 class="h5">2. &nbsp; &nbsp; &nbsp;Bons de réduction</h4>
                                <ol><li>Des bons de réduction promotionnels utilisables sur AyaMarket.be peuvent être envoyés de temps en temps par e-mail. Ces bons de réduction promotionnels sont uniquement utilisables pour des achats en ligne.</li>
                                    <li>Les bons de réduction promotionnels sont uniquement valables pendant la période de validité mentionnée dessus et ne peuvent être utilisés qu’une seule fois. Les conditions d’utilisation sont également indiquées dessus (marques et articles concernés, montant minimum d’achat…)</li>
                                    <li>Si vous avez utilisé un bon de réduction promotionnel avec un montant minimum d’achat lors de votre commande, nous nous réservons le droit de vous facturer le prix initial de la marchandise au cas où, en raison d'une rétractation, le montant total de la commande se retrouve inférieur au montant minimum requis pour l’utilisation de ce bon de réduction.</li>
                                </ol><p>Les bons de réductions et ristournes peuvent être cumulés en ligne tant que leur valeur totale ne dépasse pas le montant des achats. Il est impossible d’utiliser les bons de réductions, ristournes sur une commande déjà passée. En cas de fraude, de tentative de tromperie ou de soupçon d’activités illégales liés à une commande payée sur l’eshop AyaMarket, nous nous réservons le droit de clôturer les comptes clients correspondants, leur fidélité et/ou de demander le règlement de la commande via un mode de paiement différent.</p>
                                <p style="text-align:right;"><a href="#haut">↑ Haut</a></p>
                                <h2 class="h4"><a name="retours"></a>ARTICLE 11 - POLITIQUE EN MATIÈRE DE RETOURS</h2>
                                <p>Nous vous proposons 2 moyens de retour (attention uniquement valable pour des achats effectués en ligne et non en magasin):</p>
                                <h4 class="h5">1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; En magasin</h4>
                                <ul><li>Sur présentation du bon de retour, le client ramène gratuitement l’article dans le magasin AyaMarket de son choix. Il peut choisir de faire un échange, recevoir un bon à valoir valable en magasin, ou encore demander le remboursement.Dans le cas où une commande est payée en partie ou totalement avec un bon à valoir ou un chèque cadeau, le remboursement se fera en partie ou totalement avec un nouveau bon à valoir.</li>
                                    <li>Dans le cas d’un un retour complet contre remboursement, nous rembourserons le montant total de la commande et les frais de livraison (s’ils étaient à votre charge)</li>
                                    <li>Dans le cas d’un retour partiel contre remboursement, les frais de livraison restent dus, nous vous remboursons uniquement le montant des articles retournées.</li>
                                    <li>En tout état de cause, les articles doivent nous être retournés dans leur état d’origine, non portés, munis de leurs étiquettes et dans leur emballage d’origine, dans un délai de 14 jours à dater de la date de livraison.</li>
                                </ul><h4 class="h5">2.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Via Bpost</h4>
                                <ul><li>Dans le cas d’un retour en ligne via Bpost ou tout autre moyen de livraison de votre choix, les frais de retour seront à votre charge. Un remboursement ou le retour contre un coupon valable en ligne sont les possibilités qui s’offrent à vous.Dans le cas où une commande est payée en partie ou totalement avec un bon à valoir ou un chèque cadeau, le remboursement se fera en partie ou totalement avec un nouveau bon à valoir.</li>
                                    <li>Pour procéder au retour, vous devez remplir les informations demandées sur le bon de retour, disponible dans votre colis et glisser le bon de retour avec les articles dans le colis.</li>
                                    <li>Dans le cas d’un retour complet contre remboursement, nous vous rembourserons le montant total de la commande et les frais de livraison (s’ils étaient à votre charge).</li>
                                    <li>Dans le cas d’un retour partiel contre remboursement, les frais de livraison restent dus, nous remboursons uniquement le montant des articles retournés. Le remboursement s’effectuera dans les 14 jours suivant la réception des articles retournés et utilisera le même moyen de paiement que celui que utilisé par le client pour la transaction initiale.</li>
                                    <li>Si vous souhaitez échanger un article, un coupon de la valeur de votre article vous sera envoyé dès la réception de votre retour afin que vous puissiez repasser votre commande. Vous n’aurez pas de nouveaux frais de livraison s’il s’agit d’un retour partiel. Le coupon est utilisable sur tout achat d’au moins la valeur du coupon</li>
                                    <li>En tout état de cause, les articles doivent nous être retournés dans leur état d’origine, non portés, munis de leurs étiquettes et dans leur emballage d’origine, dans un délai de 14 jours à dater de la date de livraison.</li>
                                </ul><h2 class="h4"><a></a>ARTICLE 12 - POLITIQUE EN MATIÈRE DE RÉSERVATION</h2>
                                <ol><li>AyaMarket se réserve le droit de refuser la possibilité de réserver en cas d’abus du service par le client.</li>
                                </ol><ol start="2"><li>La réservation n’est effective qu’à partir du moment où la pièce aura été mise de côté dans le magasin choisi. Un mail vous sera envoyé à ce moment-là pour vous confirmer votre réservation et vous informer de la disponibilité du produit dans ce magasin. Si la pièce n’est pas directement disponible dans le magasin choisi, un mail vous sera envoyé pour vous informer de son transfert entre magasins.</li>
                                </ol><ol start="3"><li>Les articles seront réservés à votre nom dans le magasin AyaMarket de votre choix et ce pendant 7 jours ouvrables&nbsp;(3 jours ouvrables en période de soldes et prix réduits). Ce service est gratuit.</li>
                                </ol><ol start="4"><li>Le paiement des articles s’effectuera en magasin, au prix effectif lors du jour du retrait de la réservation. Un prix promotionnel ne sera pas bloqué au-delà de sa période d'action. Les articles réservés en magasin ne peuvent être retournés qu’en magasin.</li>
                                </ol><ol start="5"><li>Les articles achetés dans le cadre d’une réservation ne sont pas soumis au délai de rétractation.</li>
                                </ol><h2 class="h4"><a></a>ARTICLE 13 - PRODUITS DÉFECTUEUX</h2>
                                <ol><li>AyaMarket garantit l’état intact du produit lors de sa livraison et sa conformité aux informations du fabricant. L’utilisation du produit doit être suivre les instructions publiées par le fabricant, décrites dans la description du produit. Vous devez vous assurer que vous utilisez le produit conformément à ces instructions.</li>
                                </ol><ol start="2"><li>Nous nous employons à vous livrer des produits dans un parfait état. Cependant, si vous signalez que le produit est défectueux, vous acceptez de garder le produit dans son état actuel afin que nous puissions l’examiner dans un délai raisonnable.</li>
                                </ol><ol start="3"><li>Nous pouvons requérir votre aide ainsi que certaines informations relatives au produit, comprenant des détails quant à la manière dont le produit est supposé être abîmé ou défectueux et l’envoi du bon de livraison complété et autres informations nécessaires, ceci afin d’apporter une solution rapide pour le produit défectueux.</li>
                                </ol><ol start="4"><li>Dans le cas où nous constatons que le produit a été mal utilisé, a subi des abus ou des négligences, en ce compris les accidents, les dommages résultant d’une tentative de modification ou réparation, les dégâts dus à une usure normale régulière ainsi que toute autre action inadéquate par rapport à son utilisation, telle que préconisée par le fabricant, et ceci après la livraison, AyaMarket se réserve le droit de ne pas remplacer ni de vous rembourser le produit.</li>
                                </ol><p>&nbsp;</p>
                                <h2 class="h4"><a name="force"></a>ARTICLE 14 - FORCE MAJEURE</h2>
                                <ol><li>Nous ne sommes pas tenus de respecter nos obligations si un cas de force majeure se produit. Dans ce cas, nous pouvons soit suspendre nos obligations pendant la durée du cas de force majeure, soit résoudre définitivement le contrat.</li>
                                </ol><ol start="2"><li>Un cas de force majeure est toute circonstance indépendante de notre volonté et de notre contrôle qui entrave totalement ou partiellement le respect de nos obligations. Il s’agit entre autres des grèves, des incendies, des perturbations de l’activité, de l’approvisionnement d’énergie, d’un réseau (de télécommunication) ou d’une connexion ou des systèmes de communication utilisés et/ou de l’indisponibilité à un moment quelconque du Site Internet, de la livraison en retard ou de l’absence de livraison par des sous-traitants ou autres tiers auxquels nous avons fait appel,…</li>
                                </ol><p>&nbsp;</p>
                                <h2 class="h4"><a></a>ARTICLE 15 - PROPRIÉTÉ INTELLECTUELLE</h2>
                                <ol><li>Notre site Internet, nos logos, textes, photos, noms et, de manière générale, l’ensemble de notre communication sont protégés par nos droits de la propriété intellectuelle, ceux de nos sous-traitants ou autres ayants droit.</li>
                                </ol><ol start="2"><li>Il est interdit d’utiliser et/ou d'apporter des modifications aux droits de la propriété intellectuelle décrits dans le présent article. Il est ainsi interdit de copier ou de reproduire des dessins, photos, textes, combinaisons de couleur des logos, etc. sans notre autorisation écrite préalable et expresse.</li>
                                </ol><h2 class="h4"><a name="litiges"></a>ARTICLE 16 - TRAITEMENT DES RÉCLAMATIONS ET LITIGES</h2>
                                <ol><li>Nous espérons bien entendu toujours satisfaire pleinement nos clients. Si vous avez toutefois des réclamations à formuler à propos de nos biens ou services, vous pouvez vous adresser à notre service client :</li>
                                </ol><p>par e-mail à Admin@AyaMarket.be ; via notre <a title="Nous contacter" href="https://www.AyaMarket.be/contact">formulaire de contact</a> disponible sur notre site web&nbsp;; ou par téléphone au +32 (0)87/30.60.29 Notre service clientèle est joignable du lundi au jeudi de 8h30 à 17h00 et le vendredi de 08h30 à 12h30. Nous mettrons tout en œuvre pour traiter votre réclamation dans les 7 jours.</p>
                                <ol start="2"><li>Tous les contrats que nous concluons avec nos clients sont, indépendamment de leur lieu de domicile, exclusivement régis par le droit belge et seuls les tribunaux belges ayant juridiction sont compétents pour connaître des litiges éventuels. Si un autre droit était applicable pour des motifs de droit international, il serait avant tout fait référence, pour l’interprétation des présentes conditions générales, à la législation belge sur les pratiques du marché et la protection des consommateurs.</li>
                                    <li>Vous souhaitez introduire une plainte ? Vous pouvez le faire via<a class="link" href="http://ec.europa.eu/consumers/odr/">&nbsp;la plateforme de la Commission Européenne</a> en accord avec le&nbsp;règlement européen n° 524/2013 relatif au règlement en ligne des litiges de consommation (applicable depuis le&nbsp;9 janvier 2016).</li>
                                </ol><p><a href="#haut">↑ Haut</a></p>
                            </div>
                        </div>
                    </section>
                </section>
            </div>
        </div>
    </div>

@endsection
